raw: true # default: false
killOthers: true # default: false
commands: # required will be run concurrently
  - command: "echo 'Hello, World!'" # required
    name: "" # optional
    prefixColor: green
    raw: false # optional overrides the global raw option
  - command: "sleep 5" # required
    name: "" # optional
    prefixColor: red
    raw: false # optional overrides the global raw option

runBefore: # default: [] will be run seqyentially after the commands
  raw: true # default true
  commands:
    - command: "echo 'Before all things!'" # required
      name: "hello" # default: ""
      raw: true # default: ../raw
      input: none # default: none; options: stdin, previous, none
      output: stdout # default: stdout; options: stdout, next, none

runAfter: # default: [] will be run seqyentially after the commands
  raw: true # default true
  commands:
    - command: "echo 'Run After everything'" # required
      always: true # default: false
      name: "hello" # default: ""
      raw: true # default: ../raw
      input: none # default: none; options: stdin, previous, none
      output: stdout # default: stdout; options: stdout, next, none
