# yaml-language-server: $schema=config.schema.json
raw: true # default: false
killOthers: false # default: false
killOthersOnFail: false # default: false
debug: false # default: false
prefixType: name # default: ""
commands: # required will be run concurrently
  - command: "echo 'Hello, World!'" # required
    name: "" # optional
    color: green
    bold: true
    underline: false
    raw: false # optional overrides the global raw option
  - command: "sleep 2" # required
    name: "" # optional
    color: "#ff0000"
    bold: true
    raw: false # optional overrides the global raw option

runBefore: # default: [] will be run seqyentially after the commands
  raw: true # default true
  commands:
    - command: "echo 'Before all things!'" # required
      name: "hello" # default: ""
      raw: true # default: ../raw

runAfter: # default: [] will be run seqyentially after the commands
  raw: true # default true
  commands:
    - command: "echo 'Run After everything'" # required
      name: "hello" # default: ""
      raw: true # default: ../raw
