# yaml-language-server: $schema=config.schema.json
raw: true # default: false
killOthers: false # default: false
killOthersOnFail: false # default: false
killSignal: SIGTERM # default: SIGINT
debug: false # default: false
prefix:
  template: name # default: ""
  padPrefix: true
  prefixLength: 10
  timestampFormat: "15:04:05.000"
  timeSinceStart: true
commands: # required will be run concurrently
  - command: "echo 'Hello, World!'" # required
    name: "" # optional
    color: green
    bold: true
    underline: false
  - command: "sleep 2" # required
    name: "" # optional
    color: "#ff0000"
    bold: true

runBefore: # default: [] will be run seqyentially after the commands
  commands:
    - command: "echo 'Before all things!'" # required
      name: "hello" # default: ""

runAfter: # default: [] will be run seqyentially after the commands
  commands:
    - command: "echo 'Run After everything'" # required
      name: "hello" # default: ""
